---
image: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  CI_DEBUG_TRACE: "false"

before_script:
  - nohup sh -c /usr/local/bin/dockerd-entrypoint.sh &
  - sleep 2;

stages:
  - tests

stage-tests:
  stage: tests
  tags:
    - privileged-runner
  script:
    - apk add --update python py-pip python-dev gcc libc-dev libffi-dev openssl-dev linux-headers make
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements-tests.txt
    - molecule test
