---
galaxy_info:
  author: pulibrary
  description: nginx role
  company: pulibrary

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

dependencies: []
