---
- name: Search_app | create system user group
  ansible.builtin.group:
    name: "{{ deploy_user }}"

- name: Search_app | create system user
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    home: "/home/{{ deploy_user }}"
    shell: "{{ deploy_user_shell }}"

# this task uses the '*.keys' GitHub URLs to access key contents
# the contents are used in a template two tasks further down
- name: Search_app | get key content from github
  ansible.builtin.command: 'curl {{ item }}'
  loop: "{{ deploy_user_github_keys }}"
  register: deploy_user_keys_from_github
  changed_when: false
  run_once: true
  tags: update_keys

- name: Search_app | create the .ssh directory
  ansible.builtin.file:
    path: "/home/{{ deploy_user }}/.ssh/"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0700"

- name: Search_app | build authorized keys file
  ansible.builtin.template:
    src: authorized_keys.j2
    dest: /home/{{ deploy_user }}/.ssh/authorized_keys
    group: "{{ deploy_user }}"
    owner: "{{ deploy_user }}"
    mode: '0600'
    backup: true
  tags: update_keys

- name: Search_app | allow "authorized_key" files
  ansible.builtin.lineinfile: >
              dest=/etc/ssh/sshd_config
              state=present
              backrefs=yes
              regexp='^#AuthorizedKeysFile(.*?)$'
              line="AuthorizedKeysFile\1"
  when:
    - running_on_server

- name: Search_app | allow deploy user to SSH
  ansible.builtin.lineinfile: >
              dest=/etc/ssh/sshd_config
              state=present
              backrefs=yes
              regexp='^AllowUsers(.*?)( ?)({{ deploy_user }})?$'
              line="AllowUsers\1 {{ deploy_user }}"
  when:
    - running_on_server
  notify:
    - restart sshd

- name: Search_app | install deploy github ssh config
  ansible.builtin.copy:
    src: files/ssh_config
    dest: "/home/{{ deploy_user }}/.ssh/config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0644"
  register: deploy_ssh_config

- name: Search_app | set sudo options for {{ deploy_user }}
  ansible.builtin.template:
    src: sudo.j2
    dest: "/etc/sudoers.d/{{ deploy_user }}"
    mode: "0600"
  when:
    - sudo_options is defined
  loop_control:
    label: "{{ deploy_user }}"

- name: Search_app | Run all handlers notified by the deploy_user role
  ansible.builtin.meta: flush_handlers
  changed_when: false
