---
- name: Search_app | Download solr
  ansible.builtin.get_url:
    url: https://pulmirror.princeton.edu/mirror/solr/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
    dest: /tmp
    mode: "0755"

- name: Search_app | copy solr_install script
  ansible.builtin.copy:
    src: install_solr_service.sh
    dest: /tmp/install_solr_service.sh
    mode: "0755"

- name: Search_app | install Solr as a service (using the provided script)
  ansible.builtin.shell:
    cmd: /tmp/install_solr_service.sh /tmp/solr-8.11.3.tgz
  become: true
  become_user: root
