---
- name: Search_app | Download solr
  ansible.builtin.get_url:
    url: https://pulmirror.princeton.edu/mirror/solr/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
    dest: /tmp
    mode: "0755"

- name: Search_app | Unarchive Solr
  ansible.builtin.unarchive:
    src: /tmp/solr-{{ solr_version }}.tgz
    dest: /opt
    remote_src: true
