---
- name: Installs wget and prints the result
  hosts: all
  become: true
  tasks:
    - name: Install wget package
      ansible.builtin.apt:
        name: wget
        state: present
      register: install_result
 
    - name: debug results
      ansible.builtin.debug:
        var: install_result
